import {
  RiHomeLine,
  RiSearch2Line,
  RiRestartLine,
  RiArrowRightLine,
  RiUser4Fill,
  RiOrganizationChart,
  RiSettingsFill,
  RiLogoutCircleRLine,
  RiLandscapeFill,
  RiSendPlaneLine,
  RiCloseLine,
  RiPencilLine,
  RiUserAddLine,
  RiMenFill,
  RiWomenFill,
  RiCheckFill,
  RiProfileLine,
  RiKey2Line,
  RiMapPin5Line,
  RiGroup2Line,
  RiForbid2Line,
} from 'angular-remix-icon';

export const iconsConfig = {
  RiHomeLine,
  RiSearch2Line,
  RiRestartLine,
  RiArrowRightLine,
  RiUser4Fill,
  RiOrganizationChart,
  RiSettingsFill,
  RiLogoutCircleRLine,
  RiLandscapeFill,
  RiSendPlaneLine,
  RiCloseLine,
  RiPencilLine,
  RiUserAddLine,
  RiMenFill,
  RiWomenFill,
  RiCheckFill,
  RiProfileLine,
  RiKey2Line,
  RiMapPin5Line,
  RiGroup2Line,
  RiForbid2Line,
};
